# Generated by Django 3.2.1 on 2021-05-05 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudiobookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Audiobook', models.FileField(upload_to='Audiobook/')),
                ('Auther', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('UploadeDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SongModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Song', models.FileField(upload_to='Song/')),
                ('Duration', models.PositiveIntegerField()),
                ('UploadeDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PodcastModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Podcast', models.FileField(upload_to='Podcast/')),
                ('Duration', models.PositiveIntegerField()),
                ('UploadeDate', models.DateTimeField()),
                ('Host', models.CharField(max_length=100)),
                ('Participants', models.ManyToManyField(related_name='Participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
